spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: test
---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/spring_boot_test?currentSchema=testing'
    username: postgres
    password: 1234
  config:
    activate:
      on-profile: dev
---

spring:
  datasource:
    url: 'jdbc:h2:file:./db'
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  config:
    activate:
      on-profile: test
